# SwiftLint configuration for SnapClient iOS

included:
  - SnapClient

excluded:
  - SnapClientCore
  - build
  - Pods
  - .build

# Rule configuration
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_comments: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 50
  error: 80

# Disabled rules
disabled_rules:
  - trailing_comma
  - opening_brace
  - identifier_name  # Allow short names like 'id', 'ip'

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Custom rules
custom_rules:
  no_print:
    name: "No print statements"
    regex: "\\bprint\\s*\\("
    message: "Use os_log or Logger instead of print"
    severity: warning
